exports.JavaScriptList = [
  "JavaScript/DOM.md",
  "JavaScript/Web-Storage",
  "JavaScript/airbnb-javascript-style-guide",
  "JavaScript/ajax",
  "JavaScript/array-shuffle",
  "JavaScript/bom",
  "JavaScript/box-javascript-refactoring",
  "JavaScript/browser-compability",
  "JavaScript/call-apply",
  "JavaScript/call-by-sharing",
  "JavaScript/closure",
  "JavaScript/date-type",
  "JavaScript/disable-body-scrolling",
  "JavaScript/es2015-classes",
  "JavaScript/es2015",
  "JavaScript/es6-generators",
  "JavaScript/event-bubbling",
  "JavaScript/event-delegation",
  "JavaScript/event-target-vs-currunttarget",
  "JavaScript/event",
  "JavaScript/graph-ql",
  "JavaScript/indexeddb",
  "JavaScript/javascript-assign-function-without-run",
  "JavaScript/javascript-codeschool",
  "JavaScript/javascript-design-pattern",
  "JavaScript/javascript-download-from-get-url",
  "JavaScript/javascript-run-function",
  "JavaScript/javascript-switch-with-regex",
  "JavaScript/javascript-template-handlebar",
  "JavaScript/javascript-tips",
  "JavaScript/javascript-unlock",
  "JavaScript/jpub-ajax-json",
  "JavaScript/jquery-plugin",
  "JavaScript/js-unit-test",
  "JavaScript/map",
  "JavaScript/meteor",
  "JavaScript/mobile-web",
  "JavaScript/okky-conference",
  "JavaScript/print-page",
  "JavaScript/promise",
  "JavaScript/prototype",
  "JavaScript/reference-type",
  "JavaScript/regular-expression",
  "JavaScript/short-circuit",
  "JavaScript/sparse-array-vs-dense-array",
  "JavaScript/udemy-react",
  "JavaScript/udemy-vue",
  "JavaScript/vuejs",
  "JavaScript/way-to-get-javascript-in-html",
  "JavaScript/bugs-in-ios8",
  "JavaScript/functional-programming",
  "JavaScript/functional-programming-with-lodash-fp",
  "JavaScript/typescript",
  "JavaScript/plz-answer",
];

exports.MILList = [
  "System-Security/Shellshock.md"
];

exports.ProgramLangList = [
  "Programming-Languages/Inductive_Definition(1).md",
  "Programming-Languages/Inductive_Definition(2).md",
  "Programming-Languages/BasicsofOCaml.md",
  "Programming-Languages/RecursiveandHigher-OrderProgramming(1).md",
  "Programming-Languages/RecursiveandHigher-OrderProgramming(2).md",
  "Programming-Languages/Designandimplementation.md"
];

// exports.SystemList = [
//   "System-Security/SetUID_01.md",
//   "System-Security/SetUID_02.md",
//   "System-Security/EnvironmentVariables01.md",
//   "System-Security/EnvironmentVariables01(2).md",
//   "System-Security/EnvironmentVariables02.md",
//   "System-Security/Shellshock.md",
//   "System-Security/Buffer_overflow.md"
// ];